### ISSUE TITLE
2.4.0 not compiling

### ISSUE THREAD

**Issue by RMVincentF** [markdirish/node-odbc#206]
Hi, 

Version 2.4.0 does not compile on windows.

Here's the full stack trace. I was working on 2.3.6.

My windows is in french, sorry about that.

I think it has something to do with the fixe : BIGINT fields are now bound by default correctly

Thanks!

> odbc@2.4.0 install C:\RMGitLab\Micro-Services\AuthenticationService\node_modules\odbc
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/markdirish/node-odbc/releases/download/v2.4.0/odbc-v2.4.0-win32-x64-napi-v6.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for odbc@2.4.0 and node@14.17.3 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/markdirish/node-odbc/releases/download/v2.4.0/odbc-v2.4.0-win32-x64-napi-v6.tar.gz
Les projets sont générés individuellement dans cette solution. Pour activer la génération en parallèle, ajoutez le commutateur "/m".
  odbc.cpp
  odbc_connection.cpp
  odbc_statement.cpp
  odbc_cursor.cpp
  dynodbc.cpp
  win_delay_load_hook.cc
c:\rmgitlab\micro-services\authenticationservice\node_modules\odbc\src\odbc.cpp(630): error C2039: 'IsBigInt' : n'est pas membre de 'Napi::Value' [C:\RMGitLab\Micro-Services\AuthenticationService\node_modules
\odbc\build\odbc.vcxproj]
  c:\node_modules\node-addon-api\napi.h(190): note: voir la déclaration de 'Napi::Value'
c:\rmgitlab\micro-services\authenticationservice\node_modules\odbc\src\odbc.cpp(634): error C2039: 'BigInt' : n'est pas membre de 'Napi' [C:\RMGitLab\Micro-Services\AuthenticationService\node_modules\odbc\bui
ld\odbc.vcxproj]
  c:\node_modules\node-addon-api\napi-inl.h(15): note: voir la déclaration de 'Napi'
c:\rmgitlab\micro-services\authenticationservice\node_modules\odbc\src\odbc.cpp(634): error C2065: 'BigInt' : identificateur non déclaré [C:\RMGitLab\Micro-Services\AuthenticationService\node_modules\odbc\bui
ld\odbc.vcxproj]
c:\rmgitlab\micro-services\authenticationservice\node_modules\odbc\src\odbc.cpp(634): error C2672: 'Napi::Value::As' : fonction correspondante surchargée introuvable [C:\RMGitLab\Micro-Services\Authentication
Service\node_modules\odbc\build\odbc.vcxproj]
c:\rmgitlab\micro-services\authenticationservice\node_modules\odbc\src\odbc.cpp(634): error C2974: 'Napi::Value::As' : argument modèle non valide pour 'T', type attendu [C:\RMGitLab\Micro-Services\Authenticat
ionService\node_modules\odbc\build\odbc.vcxproj]
  c:\node_modules\node-addon-api\napi.h(265): note: voir la déclaration de 'Napi::Value::As'
c:\rmgitlab\micro-services\authenticationservice\node_modules\odbc\src\odbc_connection.cpp(1141): error C2039: 'BigInt' : n'est pas membre de 'Napi' [C:\RMGitLab\Micro-Services\AuthenticationService\node_modu
les\odbc\build\odbc.vcxproj]
  c:\node_modules\node-addon-api\napi-inl.h(15): note: voir la déclaration de 'Napi'
c:\rmgitlab\micro-services\authenticationservice\node_modules\odbc\src\odbc_connection.cpp(1141): error C3083: 'BigInt' : le symbole situé à gauche de '::' doit être un type [C:\RMGitLab\Micro-Services\Authen
ticationService\node_modules\odbc\build\odbc.vcxproj]
c:\rmgitlab\micro-services\authenticationservice\node_modules\odbc\src\odbc_connection.cpp(1141): error C2039: 'New' : n'est pas membre de 'Napi' [C:\RMGitLab\Micro-Services\AuthenticationService\node_modules
\odbc\build\odbc.vcxproj]
  c:\node_modules\node-addon-api\napi-inl.h(15): note: voir la déclaration de 'Napi'
c:\rmgitlab\micro-services\authenticationservice\node_modules\odbc\src\odbc_connection.cpp(1141): error C2664: 'Napi::Reference<Napi::Object> Napi::Reference<Napi::Object>::New(const T &,uint32_t)' : impossib
le de convertir l'argument 1 de 'Napi::Env' en 'const T &' [C:\RMGitLab\Micro-Services\AuthenticationService\node_modules\odbc\build\odbc.vcxproj]
          with
          [
              T=Napi::Object
          ]
  c:\rmgitlab\micro-services\authenticationservice\node_modules\odbc\src\odbc_connection.cpp(1141): note: Raison : impossible de convertir de 'Napi::Env' en 'const T'
          with
          [
              T=Napi::Object
          ]
  c:\rmgitlab\micro-services\authenticationservice\node_modules\odbc\src\odbc_connection.cpp(1141): note: Aucun opérateur de conversion définie par l'utilisateur disponible qui puisse effectuer cette conversi
  on, ou l'opérateur ne peut pas être appelé
c:\rmgitlab\micro-services\authenticationservice\node_modules\odbc\src\odbc_connection.cpp(1148): error C2039: 'BigInt' : n'est pas membre de 'Napi' [C:\RMGitLab\Micro-Services\AuthenticationService\node_modu
les\odbc\build\odbc.vcxproj]
  c:\node_modules\node-addon-api\napi-inl.h(15): note: voir la déclaration de 'Napi'
c:\rmgitlab\micro-services\authenticationservice\node_modules\odbc\src\odbc_connection.cpp(1148): error C3083: 'BigInt' : le symbole situé à gauche de '::' doit être un type [C:\RMGitLab\Micro-Services\Authen
ticationService\node_modules\odbc\build\odbc.vcxproj]
c:\rmgitlab\micro-services\authenticationservice\node_modules\odbc\src\odbc_connection.cpp(1148): error C2039: 'New' : n'est pas membre de 'Napi' [C:\RMGitLab\Micro-Services\AuthenticationService\node_modules
\odbc\build\odbc.vcxproj]
  c:\node_modules\node-addon-api\napi-inl.h(15): note: voir la déclaration de 'Napi'
c:\rmgitlab\micro-services\authenticationservice\node_modules\odbc\src\odbc_connection.cpp(1148): error C2664: 'Napi::Reference<Napi::Object> Napi::Reference<Napi::Object>::New(const T &,uint32_t)' : impossib
le de convertir l'argument 1 de 'Napi::Env' en 'const T &' [C:\RMGitLab\Micro-Services\AuthenticationService\node_modules\odbc\build\odbc.vcxproj]
          with
          [
              T=Napi::Object
          ]
  c:\rmgitlab\micro-services\authenticationservice\node_modules\odbc\src\odbc_connection.cpp(1148): note: Raison : impossible de convertir de 'Napi::Env' en 'const T'
          with
          [
              T=Napi::Object
          ]
  c:\rmgitlab\micro-services\authenticationservice\node_modules\odbc\src\odbc_connection.cpp(1148): note: Aucun opérateur de conversion définie par l'utilisateur disponible qui puisse effectuer cette conversi
  on, ou l'opérateur ne peut pas être appelé
c:\rmgitlab\micro-services\authenticationservice\node_modules\odbc\src\odbc_connection.cpp(1768): warning C4477: 'sprintf' : la chaîne de format '%s' nécessite un argument de type 'char *', mais l'argument va
riadique 2 est de type 'SQLTCHAR *' [C:\RMGitLab\Micro-Services\AuthenticationService\node_modules\odbc\build\odbc.vcxproj]
  c:\rmgitlab\micro-services\authenticationservice\node_modules\odbc\src\odbc_connection.cpp(1768): note: utilisez '%ls' dans la chaîne de format
  c:\rmgitlab\micro-services\authenticationservice\node_modules\odbc\src\odbc_connection.cpp(1768): note: utilisez '%lls' dans la chaîne de format
  c:\rmgitlab\micro-services\authenticationservice\node_modules\odbc\src\odbc_connection.cpp(1768): note: utilisez '%Ls' dans la chaîne de format
  c:\rmgitlab\micro-services\authenticationservice\node_modules\odbc\src\odbc_connection.cpp(1768): note: utilisez '%ws' dans la chaîne de format
c:\rmgitlab\micro-services\authenticationservice\node_modules\odbc\src\odbc_connection.cpp(3508): error C2039: 'BigInt' : n'est pas membre de 'Napi' [C:\RMGitLab\Micro-Services\AuthenticationService\node_modu
les\odbc\build\odbc.vcxproj]
  c:\node_modules\node-addon-api\napi-inl.h(15): note: voir la déclaration de 'Napi'
c:\rmgitlab\micro-services\authenticationservice\node_modules\odbc\src\odbc_connection.cpp(3508): error C3083: 'BigInt' : le symbole situé à gauche de '::' doit être un type [C:\RMGitLab\Micro-Services\Authen
ticationService\node_modules\odbc\build\odbc.vcxproj]
c:\rmgitlab\micro-services\authenticationservice\node_modules\odbc\src\odbc_connection.cpp(3508): error C2039: 'New' : n'est pas membre de 'Napi' [C:\RMGitLab\Micro-Services\AuthenticationService\node_modules
\odbc\build\odbc.vcxproj]
  c:\node_modules\node-addon-api\napi-inl.h(15): note: voir la déclaration de 'Napi'
c:\rmgitlab\micro-services\authenticationservice\node_modules\odbc\src\odbc_connection.cpp(3508): error C3861: 'New' : identificateur introuvable [C:\RMGitLab\Micro-Services\AuthenticationService\node_modules
\odbc\build\odbc.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\RMGitLab\\Micro-Services\\AuthenticationService\\node_modules\\odbc\\lib\\bindings\\napi-v6\\odbc.node" "--module_name=odbc" "--module_path=C:\\RMGitLab\\Micro-Services\\AuthenticationService\\node_modules\\odbc\\lib\\bindings\\napi-v6" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
gyp ERR! cwd C:\RMGitLab\Micro-Services\AuthenticationService\node_modules\odbc
gyp ERR! node -v v14.17.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\RMGitLab\Micro-Services\AuthenticationService\node_modules\odbc\lib\bindings\napi-v6\odbc.node --module_name=odbc --module_path=C:\RMGitLab\Micro-Services\AuthenticationService\node_modules\odbc\lib\bindings\napi-v6 --napi_version=8 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\RMGitLab\Micro-Services\AuthenticationService\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Windows_NT 10.0.19042
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\RMGitLab\\Micro-Services\\AuthenticationService\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\RMGitLab\Micro-Services\AuthenticationService\node_modules\odbc
node-pre-gyp ERR! node -v v14.17.3
node-pre-gyp ERR! node-pre-gyp -v v1.0.5
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\RMGitLab\Micro-Services\AuthenticationService\node_modules\odbc\lib\bindings\napi-v6\odbc.node --module_name=odbc --module_path=C:\RMGitLab\Micro-Services\AuthenticationService\node_modules\odbc\lib\bindings\napi-v6 --napi_version=8 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! odbc@2.4.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the odbc@2.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\VincentF\AppData\Roaming\npm-cache\_logs\2021-07-12T11_43_24_267Z-debug.log

**Comment by kadler** [comment]
Seems to be complaining that bigint is not defined. BigInt support requires N-API > 5: https://github.com/nodejs/node-addon-api/blob/main/napi.h#L122-L124 which is supported on [Node 14.0+](https://nodejs.org/api/n-api.html#n_api_node_api_version_matrix) and the command even says it's compiling for a version higher than 5: `--napi_version=8 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6` (though it's a bit confusing to me why it says both 8 and 6, but regardless they're both greater than 5).

@markdirish might want to chime in, but it seems like maybe this is a bug for https://github.com/nodejs/node-addon-api/issues

**Comment by markdirish** [comment]
This one is making me scratch my head a little as well. I was able to install on my windows machine running Node.js v14, targeting NAPI v6. I think that `--napi_version=8 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6` indicates that the highest `napi_version` for Node.js is 8, but we are targeting 6 (`node-pre-gyp` needs us to target particular versions, because the binaries become tagged, for various reasons).

@RMVincentF , was this a fresh install of `odbc`, or did you run `npm upgrade`? It is possible that your `node-addon-api` is itself out of date, and I haven't update the package-lock.json correctly. Could you run `npm list` and see what version of node-addon-api` it lists? Looks like I have `3.2.1` and it works well.

**Comment by RMVincentF** [comment]
@markdirish  It is a fresh install of odbc. I created a new project then installed odbc as a dependency.

Here's the result of npm list for the package:
| +-- odbc@2.3.6
| | +-- async@3.2.0
| | +-- node-addon-api@1.7.2

Here's my project's dependencies:
 "dependencies": {
    "odbc": "^2.3.6",
    "sqlstring": "^2.3.2",
    "typescript": "^4.2.4"
  },
  "devDependencies": {
    "@types/node": "^15.3.0"
  }

Let me know if you need more informations

Thanks!

**Comment by markdirish** [comment]
That definitely looks like the problem. In 2.4.0, `node-addon-api` version 3.0.2 or higher is required: https://github.com/markdirish/node-odbc/blob/master/package.json#L43 . I don't know if it did or didn't update when you tried installing odbc v.2.4.0 before, but your error would make sense if it didn't: Before a certain node-addon-api version, BigInt, was hidden inside a `NAPI_EXPERIMENTAL` ifded; Afterwards, it was moved to be hidden behind a particular `NAPI_VERSION`, so we no longer define `NAPI_EXPERIMENTAL`.

In your output however, it even looks like `odbc` is still the old version as well. **I would try running `npm install node-addon-api@3.2.1` to see if that updates for you, and once that is ^3.0.2, try installing `odbc@2.4.0`.**

**Comment by RMVincentF** [comment]
@markdirish 

I'm still getting the same issue :/

I know have this in npm list : 
+-- node-addon-api@3.2.1
+-- odbc@2.3.6
| +-- async@3.2.0
| +-- node-addon-api@1.7.2

And my package.json looks like this : 
"dependencies": {
    "node-addon-api": "^3.2.1",
    "odbc": "^2.3.6",
    "sqlstring": "^2.3.2",
    "typescript": "^4.2.4"
  },
  "devDependencies": {
    "@types/node": "^15.3.0"
  }

**Comment by markdirish** [comment]
I'm not sure why it would say `odbc@2.3.6` if it was a fresh install of `odbc`. I would just try to remove `odbc` (and the standalone `node-addon-api`), and then install odbc again:

```
npm uninstall odbc
npm install node-addon-api
npm install odbc
(or npm install odbc@2.4.0)
```

Maybe even try to install `odbc` in a completely clean application/directory, that should tell you if the problem is a bad version of `node-addon-api` or if it really can't compile as written.

**Comment by RMVincentF** [comment]
I try to install odbc inside a new app/directory and I'm still having the same issue.
I also clean my npm cache with npm cache clean --force by it did not fix the issue

**Comment by lamuertepeluda** [comment]
I am facing this problem on CentOS 7 with Node 16. On Ubuntu or Debian it works, same as for CentOS with Node 14... but I need it to work on 16 _also_ on CentOS.

Any ideas?

**Comment by lamuertepeluda** [comment]
The error is

```bash
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! g++: error: unrecognized command line option ‘-std=gnu++14’
npm ERR! make: *** [Release/obj.target/odbc/src/odbc.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
```

so probably related to `g++`

**Comment by lamuertepeluda** [comment]
seems like I have g++/gcc v4.8.5 on CentOS 7 vs g++/gcc 9.3.0 on Ubuntu... I'll check whether an update fixes this 😅

**Comment by lamuertepeluda** [comment]
For those facing this problem, follow these instructions to update CentOS gcc to 9.x
https://stackoverflow.com/a/67212990/1679665

**Comment by worksofliam** [comment]
I am also having issues building on my macbook running under Node.js 12.

```
> odbc@github:worksofliam/node-odbc#0ad018268dd474cd686809b45f94c651202fad8c install /Users/liam.allan/Documents/highline-new/node_modules/odbc
> node-pre-gyp install --fallback-to-build

sh: node-pre-gyp: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! odbc@github:worksofliam/node-odbc#0ad018268dd474cd686809b45f94c651202fad8c install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the odbc@github:worksofliam/node-odbc#0ad018268dd474cd686809b45f94c651202fad8c install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/liam.allan/.npm/_logs/2021-07-30T00_02_40_005Z-debug.log
```

**Comment by markdirish** [comment]
@worksofliam I don't understand how installing @mapbox/node-pre-gyp, deleting your `node_modules`, then re-installing the package is making a difference. It would seem that you are deleting all the work you just did by installing.

It seems that somehow either you aren't getting your dependencies installed, or for whatever reasons the shell that the npm script is running can't find `node-pre-gyp`, which is installed to `node_modules/.bin` when the package is installed. As the [npm documentation notes](https://docs.npmjs.com/cli/v7/commands/npm-run-script):

> In addition to the shell's pre-existing PATH, npm run adds node_modules/.bin to the PATH provided to scripts. Any binaries provided by locally-installed dependencies can be used without the node_modules/.bin prefix.

If you change the script to `node_modules/.bin/node-pre-gyp install --fallback-to-build` does it fix the issue on first install?

**Comment by markdirish** [comment]
There are prebuilt Windows binaries now, and @worksofliam notes that the M1 compilation is working well now. Closing!
